kind: pipeline
type: docker
name: apollo-cache-aerospike

steps:
  - name: test
    image: node:10
    commands:
      - npm install
      - npm run build
      - npm run test
  # - name: npm
  #   image: plugins/npm
  #   commands:
  #     - npm install
  #     - npm run build
  #   settings:
  #     username: helipilot50
  #     password:
  #       from_secret: npm_password
  #     email: helipilot50@gmail.com
  #     folder: module/dist
trigger:
  branch:
    - develop
services:
  - name: aerospikedb
    image: aerospike/aerospike-server:latest
    environment:
      NAMESPACE: "test"
      MEM_GB: 12
