kind: pipeline
type: docker
name: apollo-cache-aerospike

steps:
  - name: build
    image: node:10
    commands:
      - npm install
      - npm run build
    when:
      branch:
        - master
        - develop
        - feature/*
  - name: test
    image: node:10
    commands:
      - npm run test
    when:
      branch:
        - master
        - develop
        - feature/*
  - name: npm
    image: plugins/npm
    settings:
      username: helipilot50
      password:
        from_secret: $${NPM_PASSWORD}
      email: helipilot50@gmail.com
      token:
        from_secret: $${NPM_TOKEN}
      folder: dist
    when:
      branch:
        - master
services:
  - name: aerospikedb
    image: aerospike/aerospike-server:latest
    environment:
      NAMESPACE: "test"
      MEM_GB: 12
